spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/volunteering_dev
  security:
    jwt:
      secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 86400000
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 928e82805cc53e
    password: 06a807f3511754
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
