spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: your_database_name
      auto-index-creation: true
      transactional: false
  mail:
    host: your.smtp.host
    port: your_smtp_port
    username: your_smtp_username
    password: your_smtp_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: your.smtp.host
        transport:
          protocol: smtp

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.backend: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO

spring.security:
  jwt:
    secret: your_jwt_secret_key_here
    expiration: 86400000  # 24 hours in milliseconds
    refresh-token:
      expiration: 604800000  # 7 days in milliseconds

security:
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

google:
  maps:
    api:
      key: your_google_maps_api_key_here

 