spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/volunteering_dev}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8080}

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}
  security:
    permit-all: true  # Allow all endpoints in dev
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  level:
    com.backend.volunteering: DEBUG
    org.springframework.security: DEBUG
