spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
    basic:
      enabled: true
    csrf:
      enabled: true
    headers:
      frame: deny
      hsts: true
      xss: true
      content-security-policy: "default-src 'self'"
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
    from: ${MAIL_FROM}
    personal: ${MAIL_PERSONAL}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:volunteering_prod}

app:
  security:
    permit-all: false
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,Cache-Control,Accept,Origin,X-Requested-With

logging:
  level:
    root: WARN
    com.backend.volunteering: INFO
    org.springframework.data.mongodb: INFO
