spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: volunteer_platform_dev
      auto-index-creation: true
      transactional: false
  mail:
    host: smtp.example.com
    port: 587
    username: your-username
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.example.com
        transport:
          protocol: smtp

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.backend: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO

spring.security:
  jwt:
    secret: your-dev-jwt-secret-key-replace-this-with-a-secure-value
    expiration: 86400000 # 24 hours
    refresh-token:
      expiration: 604800000 # 7 days

security:
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

google:
  maps:
    api:
      key: your-google-maps-api-key

app:
  frontend:
    url: http://localhost:4200
  email:
    from: no-reply@your-domain.com
