spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: volunteering-platform
  data:
    mongodb:
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}

app:
  frontend-base-url: http://localhost:4200
  frontend-url: http://localhost:4200
  jwt:
    secret: ${JWT_SECRET:your-default-secret-key}
    expiration: ${JWT_EXPIRATION:86400000}
  oauth2:
    redirectUri: ${APP_FRONTEND_URL:http://localhost:4200}/oauth2/redirect
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
