spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: volunteering-platform
  security:
    oauth2:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
  oauth2:
    redirectUri: ${APP_FRONTEND_URL}/oauth2/redirect
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
