spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/volunteering_dev
      database: volunteering_dev
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 4b8f489e24ceaf
    password: 3902504165f5f9
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: noreply@yourapp.com
    personal: Volunteering Platform

app:
  security:
    permit-all: true
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  level:
    root: INFO
    com.backend.volunteering: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb: DEBUG
