spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          google:
           client-id: 298009711197-jkuj27rigq9r1ilmtel1961km4m59ooq.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: ERROR
    org.springframework.web: WARN
    com.backend: INFO

spring.security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:86400000}

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

app:
  frontend:
    url: ${FRONTEND_URL}
  email:
    from: ${EMAIL_FROM}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  email:
    verification-expiry-hours: 24
    reset-password-expiry-hours: 1
  email:
    from: no-reply@volunteer-platform-dev.com
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1 hour
    refresh-expiration: 86400000 # 24 hours

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level - %msg%n"
  level:
    root: ERROR
    org.springframework.web: WARN
    com.backend: INFO

spring.security:
  jwt:
    secret: your-production-jwt-secret-key
    expiration: 86400000
    refresh-token:
      expiration: 604800000

security:
  cors:
    allowed-origins: https://your-frontend-domain.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

app:
  frontend:
    url: https://your-frontend-domain.com  # Production frontend URL 