spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/volunteer_platform_dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
  mail:
    host: smtp.example.com
    port: 587
    username: your-username
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO

spring.security:
  jwt:
    secret: your-dev-jwt-secret-key
    expiration: 3600000 # 1 hour
    refresh-token:
      expiration: 86400000 # 24 hours

security:
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

google:
  maps:
    api:
      key: your-google-maps-api-key

app:
  frontend:
    url: http://localhost:4200
  email:
    from: no-reply@volunteer-platform-dev.com

# ... rest of your dev configuration with example values 