spring:
  application:
    name: volunteer-platform
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
          github:
            scope:
              - user:email
              - read:user

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

app:
  email:
    verification-expiry-hours: 24
    reset-password-expiry-hours: 1

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  email:
    from: ${EMAIL_FROM:no-reply@volunteer-platform.com}

    