spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: volunteering-platform
  security:
    oauth2:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
  oauth2:
    redirectUri: ${OAUTH2_REDIRECT_URI:http://localhost:3000/oauth2/redirect}
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
