spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/volunteering_dev
      database: volunteering_dev
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ee98594ded4802
    password: 97108c4ca2db77
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          debug: true
    from: noreply@yourapp.com
    personal: Volunteering Platform

app:
  security:
    permit-all: true
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
  frontend-base-url: http://localhost:3000

logging:
  level:
    root: INFO
    com.backend.volunteering: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb: DEBUG
