spring:
  data:
    mongodb:
      uri: mongodb://prod-mongodb-uri:27017
      database: volunteer_platform_prod
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: prod-email@example.com
    password: prod-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level - %msg%n"
  level:
    root: WARN
    com.backend: INFO

spring.security:
  jwt:
    secret: your-production-jwt-secret-key
    expiration: 86400000
    refresh-token:
      expiration: 604800000

security:
  cors:
    allowed-origins: https://your-frontend-domain.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

app:
  frontend:
    url: https://your-frontend-domain.com  # Production frontend URL 