spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: volunteering-platform
  data:
    mongodb:
      auto-index-creation: true
      database: volunteering_db
      host: localhost
      port: 27017
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

server:
  port: 8080
  servlet:
    context-path: /

app:
  frontend-base-url: http://localhost:4200
  frontend-url: http://localhost:4200
  jwt:
    secret: ${JWT_SECRET:QzVDMkM4QTgyNjBGNDM0Q0E3OUZBM0Q2ODM3RjRGOTk2NDk4NDhBNDZFNzQ0NDQzMzY0NkM2NTY1NzA2MTcyNzQ2QQ==}
    expiration: ${JWT_EXPIRATION:86400000}
  oauth2:
    redirectUri: ${APP_FRONTEND_URL:http://localhost:4200}/oauth2/redirect
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}

# Add CORS configuration
cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
