spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: volunteering-platform
  data:
    mongodb:
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
  oauth2:
    redirectUri: ${APP_FRONTEND_URL}/oauth2/redirect
  frontend-url: ${APP_FRONTEND_URL}
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
