spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  security:
    jwt:
      secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
    com.backend.volunteering: INFO
