spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/volunteer_platform_dev}
  security:
    oauth2:
      client:
        registration:
          google:
           client-id: 298009711197-jkuj27rigq9r1ilmtel1961km4m59ooq.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ee98594ded4802
    password: 97108c4ca2db77
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO

spring.security:
  jwt:
    secret: 9a4f2c8d3b7e1a5f8c2d4e6b9a3f7c1e5b2d8a4c6f9e3b7d1c5a8e2f4b6d9c7a3f1e5b8a2c4f6d9e7b3c1a5f8e2d4b6c9a7f3e1b5d8a2c4f6
    expiration: 86400000 
    refresh-token:
      expiration: 604800000 

security:
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

google:
  maps:
    api:
      key: AIzaSyC3-0-00000000000000000000000000000000

app:
  frontend:
    url: http://localhost:4200
  email:
    from: no-reply@volunteer-platform-dev.com
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1 hour
    refresh-expiration: 86400000 # 24 hours

 