spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level - %msg%n"
  level:
    root: WARN
    com.backend: INFO

spring.security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:604800000}

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

app:
  frontend:
    url: ${FRONTEND_URL}
  email:
    from: ${EMAIL_FROM}
