spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: ERROR
    org.springframework.web: WARN
    com.backend: INFO

spring.security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:86400000}

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

app:
  frontend:
    url: ${FRONTEND_URL}
  email:
    from: ${EMAIL_FROM}

# ... rest of your prod configuration with environment variables 